[[redirects]]
  from = "/api/code/highlight"
  to = "/.netlify/functions/highlight-code"
  status = 200

[[redirects]]
  from = "/api/code/format"
  to = "/.netlify/functions/format-code"
  status = 200


[[redirects]]
  from = "/api/code/format-and-highlight"
  to = "/.netlify/functions/format-and-highlight-code"
  status = 200